# docker-compose.yml

version: "3.2"

networks:
  isolation-network:
    driver: bridge

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - isolation-network

  currency-service:
    build: ./currency-service
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - './currency-service:/currency-service'
      - '/currency-service/node_modules'
    links:
      - redis
    environment:
      - CURRENCY_LAYER_LEY=adbbce308048ec60418c2e50bee0b2ee
    networks:
      - isolation-network
  
  beer-service:
    build: ./beer-service
    tty: true
    ports:
      - "4000:4000"
    volumes:
      - './beer-service:/beer-service'
      - '/beer-service/node_modules'
    links:
      - redis
      - currency-service
    environment:
      - REDIS_URL=redis://cache
      - CURRENCY_SERVICE=currency-service
    networks:
      - isolation-network


# Host volumes used to store code.